# Generated by Django 4.1.4 on 2023-01-09 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
