# Generated by Django 4.1.4 on 2023-01-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('per', '0004_personal_user_alter_personal_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='user',
            new_name='created_user',
        ),
    ]
